# =====================================================================
# PART 1 — VALIDATED INPUTS
# str, int, float, bool | while + try/except | correct boolean
# CONTRIBUTOR: KABORE Albertine
# =====================================================================

def read_string(prompt: str) -> str:
    """Validated string input — re-prompts if the field is left empty."""
    while True:
        value = input(prompt).strip()
        if value:
            return value
        print("  Error: this field cannot be empty.")


def read_int(prompt: str) -> int:
    """Validated integer input — try/except prevents crash on bad input."""
    while True:
        try:
            return int(input(prompt))
        except ValueError:
            print("  Error: please enter a whole number (e.g. 28).")


def read_float(prompt: str) -> float:
    """Validated decimal input — try/except prevents crash on bad input."""
    while True:
        try:
            return float(input(prompt))
        except ValueError:
            print("  Error: please enter a decimal number (e.g. 3.5).")


def read_bool(prompt: str) -> bool:
    """
    Validated boolean input.
    CORRECT:  input().strip().lower() == "yes"  →  True / False
    WRONG:    bool(input())  →  always True for any non-empty string
    """
    while True:
        answer = input(prompt).strip().lower()
        if answer in ["yes", "y", "oui", "o"]:
            return True
        elif answer in ["no", "n", "non"]:
            return False
        print("  Error: please answer yes or no.")


# =====================================================================
# PART 2 — INHERITANCE
# Parent class, child class, super().__init__()
# CONTRIBUTOR: SIMPORE Alima
# =====================================================================

class Person:
    """Parent class — stores the identity shared by all system users."""

    def __init__(self, last_name: str, first_name: str, age: int, phone: str):
        self.last_name = last_name
        self.first_name = first_name
        self.age = age
        self.phone = phone

    def full_name(self) -> str:
        return f"{self.first_name} {self.last_name}"


class FarmerAccount(Person):
    """
    Child class — a FarmerAccount IS A Person.
    Inherits identity from Person and adds farm-specific data and methods.
    """

    total_accounts = 0

    def __init__(self, last_name: str, first_name: str, age: int, phone: str,
                 farm_size: float, crop: str, savings: float, is_coop_member: bool):

        super().__init__(last_name, first_name, age, phone)

        self.farm_size = farm_size
        self.crop = crop
        self.savings = savings
        self.is_coop_member = is_coop_member

        FarmerAccount.total_accounts += 1

    # =====================================================================
    # PART 3 — ARITHMETIC EXPRESSIONS
    # CONTRIBUTOR: GARANE Farida
    # =====================================================================

    def calculate_fees(self) -> float:
        """
        Calculation 1:
        Base membership fee (5000 FCFA)
        with 25% discount if already in a cooperative.
        """
        base_fee = 5000.0
        discount = 0.25 if self.is_coop_member else 0.0
        return base_fee * (1.0 - discount)

    def simulate_revenue(self, yield_per_ha: float, price_per_bag: float) -> float:
        """
        Calculation 2:
        Estimated gross harvest revenue.
        Formula = farm size × yield × price per bag
        """
        return self.farm_size * yield_per_ha * price_per_bag

    def calculate_interest(self, rate: float, months: int) -> float:
        """
        Calculation 3:
        Simple interest generated by savings.
        """
        return self.savings * (rate / 100) * (months / 12.0)

# =================================================================
    # PART 4 — DECORATOR AND MAGIC METHOD
    # CONTRIBUTOR: TAO Fazollah
    # =================================================================
 
    @classmethod
    def account_count(cls) -> int:
        """@classmethod — reads total_accounts, a class-level variable."""
        return cls.total_accounts
 
    def __str__(self) -> str:
        """Magic method __str__ — controls what print(object) displays."""
        status = "Cooperative" if self.is_coop_member else "Independent"
        return (
            f"  Name    : {self.full_name()}\n"
            f"  Age     : {self.age} yrs   |   Phone : {self.phone}\n"
            f"  Farm    : {self.farm_size} ha   |   Crop  : {self.crop}\n"
            f"  Status  : {status}\n"
            f"  Savings : {self.savings:,.0f} FCFA"
        )
 # =====================================================================
# MAIN
# =====================================================================
 
def main():
 
    print(f"{'=' * 58}")
    print(f"{'FASOAGRIFINANCE — MEMBER REGISTRATION':^58}")
    print(f"{'Burkina Institute of Technology':^58}")
    print(f"{'=' * 58}")
 
    print(f"\n  [ Member Identity ]\n")
    last_name  = read_string(f"  Last name      : ")          
    first_name = read_string(f"  First name     : ")          
    age        = read_int   (f"  Age            : ")          
    phone      = read_string(f"  Phone          : ")          
 
    print(f"\n  [ Farm Details ]\n")
    farm_size      = read_float(f"  Farm size (ha) : ")       
    crop           = read_string(f"  Main crop      : ")     
    savings        = read_float(f"  Savings (FCFA) : ")       
    is_coop_member = read_bool(f"  Cooperative member? (yes/no) : ")  
 
    print(f"\n  [ Financial Simulation ]\n")
    yield_per_ha = read_float(f"  Yield per ha (kg)        : ") 
    price_per_kg = read_float(f"  Price per kg (FCFA)      : ") 
    annual_rate  = read_float(f"  Annual interest rate (%) : ") 
    months       = read_int  (f"  Duration (months)        : ") 
 
    account = FarmerAccount(
        last_name, first_name, age, phone,
        farm_size, crop, savings, is_coop_member
    )
 
    fee = account.calculate_fees()
    revenue  = account.simulate_revenue(yield_per_ha, price_per_kg)
    interest = account.calculate_interest(annual_rate, months)
    net      = revenue + interest - fee
 
    print(f"\n{'=' * 58}")
    print(f"{'MEMBER SUMMARY REPORT':^58}")
    print(f"{'=' * 58}")
 
    print(f"\n  [ Farmer Profile ]")
    print(account)
 
    discount_note = f" (25% coop discount)" if is_coop_member else ""
    print(f"\n  [ Financial Summary ]")
    print(f"  Membership fee  : {fee:>12,.0f} FCFA{discount_note}")
    print(f"  Harvest revenue : {revenue:>12,.0f} FCFA")
    print(f"  Interest earned : {interest:>12,.0f} FCFA ({months} months @ {annual_rate}%)")
    print(f"  {'─' * 42}")
    print(f"  Net projection  : {net:>12,.0f} FCFA")
 
    print(f"\n  Total accounts in system : {FarmerAccount.account_count()}")
 
    print(f"\n{'=' * 58}")
    print(f"  FasoAgriFinance | BIT — May 2026")
    print(f"{'=' * 58}\n")
 
 
if __name__ == "__main__":
    main()
  
